<h4><strong>Intro</strong></h4>

<p>By providing a list of your website&#39;s pages in a sitemap, search engines may be better able to understand your site. Which can&nbsp;result in improved crawler coverage and newly added pages being listed on search engines faster.&nbsp;</p>

<p>If your site is statically hosted on a CDN but it&#39;s pages are dynamically generated by your API you&#39;ll need to consider:</p>

<ul>
	<li>how to dynamically generate your sitemap</li>
	<li>how to host the sitemap on the same domain as your statically hosted webapp</li>
</ul>

<p>In this article we&#39;ll be considering a situation where you use an aspnet core api but&nbsp;statically host your website with CloudFlare Pages.&nbsp;</p>

<h4><strong>The API</strong></h4>

<p>Lets write a simple controller method that dynamically generates our sitemap. Note that you&#39;ll need to query your database to generate the list of &#39;<strong>AllPageUrls</strong>&#39;.</p>

<pre>
<code class="language-cs">[ApiController]
[Route("api/sitemap.xml")]
public class SitemapController : ControllerBase
{
    [HttpGet]
    public async Task&lt;IActionResult&gt; Get()
    {
        var sitemapOutputBuilder = new StringBuilder();
        await using var sw = new StringWriter(sitemapOutputBuilder);

        await using (var xml = XmlWriter.Create(sw, new XmlWriterSettings { Indent = true, Encoding = Encoding.UTF8, Async = true}))
        {
            await xml.WriteStartDocumentAsync();
            xml.WriteStartElement("urlset", "http://www.sitemaps.org/schemas/sitemap/0.9");

            foreach (var pageUrl in AllPageUrls)
            {
                xml.WriteStartElement("url");
                xml.WriteElementString("loc", pageUrl);
                await xml.WriteEndElementAsync();
            }

            await xml.WriteEndElementAsync();
        }

        return File(Encoding.UTF8.GetBytes(sitemapOutputBuilder.ToString()), "application/xml");
    }
}</code></pre>

<h4>&nbsp;</h4>

<h4><strong>The CloudFlare worker</strong></h4>

<p>Now that our api is serving up our sitemap at&nbsp;&#39;https://&lt;api&gt;/api/sitemap.xml&#39; we need to create a new CloudFlare worker which will forward requests made to our site (https://&lt;site&gt;/sitemap.xml)&nbsp;on to our API (https://&lt;api&gt;/api/sitemap.xml)</p>

<pre>
<code class="language-javascript">export default {
  /**
   * Hooks into the request, and changes origin if needed
   */
  async fetch(request, env) {
    return await handleRequest(request, env).catch(
      (err) =&gt; new Response(err.stack, { status: 500 })
    );
  },
};

/**
 * @param {Request} request
 * @param {any} env
 * @returns {Promise&lt;Response&gt;}
 */
async function handleRequest(request, env) {

  if(request.url.endsWith("sitemap.xml")){
    return fetch(new Request('https://&lt;api&gt;/api/sitemap.xml', {
        headers: new Headers(request.headers),
        redirect: "manual",
    }));
  }

  return fetch(request);
}</code></pre>

<p>It&#39;s as simple as that! I hope this post has helped you and please let me know if you run into any issues.</p>
